spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/oauth-server
    username: postgres
    password: psql

server:
  port: 8090
  servlet:
    context-path: /oauth

logging:
  level:
    org.springframework.security: DEBUG
